### PR TITLE
docs: deprecate single manifest installer

### LINKED ISSUE #1063: feat(distribution): deprecate installer
We don't want to distribute capsule via installer.yaml files. Therefor we can deprecate all actions regarding to the installer yaml and add more resiliency for the chart. For most actions (e2e) (dev-setup) we already use the helm chart.

### PR DESCRIPTION
**Pull request by maxgio92**
Fixes #1063

### CODE REVIEW

**Comment by maxgio92** [comment]
Besides, the single manifest creates a `CapsuleConfiguration` named `capsule-default` which is not expected by Capsule Proxy, leading to the proxy failure.

**Comment by oliverbaehler** [comment]
@maxgio92 could you fix the semantics of the commit and pr title

**Comment by prometherion** [comment]
@maxgio92 please, may I ask you to address Oliver's requests?

**Comment by maxgio92** [comment]
Sorry @oliverbaehler @prometherion will do it ASAP

**Comment by maxgio92** [comment]
Hi @oliverbaehler, ready for review

**Review by prometherion — APPROVED** [review]

**Pull request merged**
