### PR TITLE
chore(helm): make capsule configuration name configurable via helm

### PR DESCRIPTION
**Pull request by sybnex**
As this is fixed in the helm templates we need a very hacky implementation to change this value.

We have like 150 groups which we are creating in a new configuration.
So I suggest to make this configuration templated as well.

### CODE REVIEW

**Comment by prometherion** [comment]
LGTM, may I ask you to amend the commits with the DCO and change the Pull Request title to `feat(helm): capsuleconfiguration name configurable`?

Thanks!

**Comment by sybnex** [comment]
> LGTM, may I ask you to amend the commits with the DCO and change the Pull Request title to `feat(helm): capsuleconfiguration name configurable`?
> 
> Thanks!

I tried to, but this DCO ... seems to make trouble? I'm lost here, sorry.

**Comment by maxgio92** [comment]
Hi @sybnex I got the problem, and I fixed.

JFI The current version of the DCO uses a version of Git that removed the dot (`'.'`) considering it an invalid trailing crud character ([commit](https://github.com/git/git/commit/1c04cb0744d2acdcaebc77b0e78c47efbba67fd5) ).

But I see you're using likely a Git version > 2.42, as the period is in your author name in your commit.

Thanks

**Comment by maxgio92** [comment]
Hi @sybnex, may I ask you to update the chart documentation?
I.e.:
```yml
+| manager.options.capsuleConfiguration | string | `"default"` | Change the default name of the capsule configuration name |
```

Overall LGTM

**Review by oliverbaehler — APPROVED** [review]

**Pull request merged**
